server:
  port: 8080

spring:
  application:
    name: news-api
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
  data:
    redis:
      host: ${REDIS_SERVER}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

